from pathlib import Path

from haystack import Document
from haystack.components.converters import PyPDFToDocument
from haystack.components.retrievers.in_memory import InMemoryBM25Retriever
from haystack.components.retrievers.in_memory import InMemoryEmbeddingRetriever
from haystack.document_stores.in_memory import InMemoryDocumentStore


PDF_FOLDER = Path("pdfs")


QUESTIONS = [
    "What is artificial intelligence?",
    "What is machine learning?",
    "What are the main types of machine learning?",
    "What is supervised learning?",
    "What is unsupervised learning?",
    "What is deep learning?",
    "What is natural language processing?",
    "What is a neural network?",
    "What is data preprocessing?",
    "What is model evaluation?"
]


def load_documents():
    """
    Convert all PDF files into Haystack Documents.
    """

    converter = PyPDFToDocument()

    pdf_files = sorted(PDF_FOLDER.glob("*.pdf"))

    if len(pdf_files) != 5:
        print(f"WARNING: Expected 5 PDFs but found {len(pdf_files)}.")

    print(f"\nFound {len(pdf_files)} PDF documents.")

    all_documents = []

    for pdf_file in pdf_files:
        print(f"Converting: {pdf_file.name}")

        result = converter.run(sources=[pdf_file])

        documents = result["documents"]

        for document in documents:
            document.meta["source_file"] = pdf_file.name

        all_documents.extend(documents)

    print(f"\nTotal documents/pages created: {len(all_documents)}")

    return all_documents


def build_bm25_store(documents):
    """
    Store documents for BM25 retrieval.
    """

    document_store = InMemoryDocumentStore()

    document_store.write_documents(documents)

    print("\nBM25 document store created.")
    print(
        "Documents in store:",
        document_store.count_documents()
    )

    return document_store


def run_bm25(document_store):
    """
    Run BM25 retrieval for all 10 questions.
    """

    retriever = InMemoryBM25Retriever(
        document_store=document_store
    )

    results = []

    print("\n" + "=" * 70)
    print("BM25 RETRIEVAL RESULTS")
    print("=" * 70)

    for number, question in enumerate(QUESTIONS, start=1):

        result = retriever.run(
            query=question,
            top_k=3
        )

        documents = result["documents"]

        print(f"\nQuestion {number}: {question}")

        if not documents:
            print("No documents retrieved.")
            continue

        for rank, document in enumerate(documents, start=1):

            source = document.meta.get(
                "source_file",
                "Unknown"
            )

            score = document.score

            print(
                f"\nRank {rank}"
                f"\nSource: {source}"
                f"\nScore: {score}"
                f"\nContent: {document.content[:250]}"
            )

        results.append(
            {
                "question": question,
                "documents": documents
            }
        )

    return results


def build_dense_store(documents):
    """
    Create a separate document store for dense retrieval.
    """

    dense_store = InMemoryDocumentStore(
        embedding_similarity_function="cosine"
    )

    dense_store.write_documents(documents)

    return dense_store


def run_dense(dense_store):
    """
    Dense retrieval section.

    This section uses embeddings generated by the
    Sentence Transformers integration.
    """

    try:
        from haystack_integrations.components.embedders.sentence_transformers import (
    SentenceTransformersDocumentEmbedder,
    SentenceTransformersTextEmbedder,
    )

    except ImportError:
        print(
            "\nSentence Transformers integration is not available."
        )
        print(
            "Install it with:"
        )
        print(
            "pip install haystack-ai sentence-transformers"
        )
        return []

    document_embedder = SentenceTransformersDocumentEmbedder(
        model="sentence-transformers/all-MiniLM-L6-v2"
    )

    document_embedder.warm_up()

    print("\nGenerating document embeddings...")

    embedded_documents = document_embedder.run(
        documents=dense_store.filter_documents()
    )["documents"]

    dense_store.delete_documents(
        dense_store.filter_documents()
    )

    dense_store.write_documents(
        embedded_documents
    )

    text_embedder = SentenceTransformersTextEmbedder(
        model="sentence-transformers/all-MiniLM-L6-v2"
    )

    text_embedder.warm_up()

    retriever = InMemoryEmbeddingRetriever(
        document_store=dense_store
    )

    results = []

    print("\n" + "=" * 70)
    print("DENSE RETRIEVAL RESULTS")
    print("=" * 70)

    for number, question in enumerate(QUESTIONS, start=1):

        query_embedding = text_embedder.run(
            text=question
        )["embedding"]

        result = retriever.run(
            query_embedding=query_embedding,
            top_k=3
        )

        documents = result["documents"]

        print(f"\nQuestion {number}: {question}")

        if not documents:
            print("No documents retrieved.")
            continue

        for rank, document in enumerate(documents, start=1):

            source = document.meta.get(
                "source_file",
                "Unknown"
            )

            score = document.score

            print(
                f"\nRank {rank}"
                f"\nSource: {source}"
                f"\nScore: {score}"
                f"\nContent: {document.content[:250]}"
            )

        results.append(
            {
                "question": question,
                "documents": documents
            }
        )

    return results


def save_results(filename, results):
    """
    Save retrieval results to a text file.
    """

    with open(filename, "w", encoding="utf-8") as file:

        for number, item in enumerate(
            results,
            start=1
        ):

            file.write(
                f"\nQuestion {number}: "
                f"{item['question']}\n"
            )

            for rank, document in enumerate(
                item["documents"],
                start=1
            ):

                source = document.meta.get(
                    "source_file",
                    "Unknown"
                )

                file.write(
                    f"\nRank {rank}\n"
                    f"Source: {source}\n"
                    f"Score: {document.score}\n"
                    f"Content: "
                    f"{document.content[:500]}\n"
                )

            file.write("\n" + "-" * 70 + "\n")


def main():

    print("=" * 70)
    print("W7D2 HAYSTACK RETRIEVAL")
    print("BM25 + DENSE RETRIEVAL")
    print("=" * 70)

    # ---------------------------------------------------------
    # STEP 1: Load PDFs
    # ---------------------------------------------------------

    documents = load_documents()

    if not documents:
        print("No documents were loaded.")
        return

    # ---------------------------------------------------------
    # STEP 2: BM25
    # ---------------------------------------------------------

    bm25_store = build_bm25_store(
        documents
    )

    bm25_results = run_bm25(
        bm25_store
    )

    save_results(
        "results_bm25.txt",
        bm25_results
    )

    # ---------------------------------------------------------
    # STEP 3: Dense Retrieval
    # ---------------------------------------------------------

    dense_store = build_dense_store(
        documents
    )

    dense_results = run_dense(
        dense_store
    )

    if dense_results:
        save_results(
            "results_dense.txt",
            dense_results
        )

    print("\n" + "=" * 70)
    print("PIPELINE COMPLETED")
    print("=" * 70)

    print("\nGenerated files:")

    print("results_bm25.txt")

    if dense_results:
        print("results_dense.txt")


if __name__ == "__main__":
    main()